# Generated by Django 5.2.3 on 2025-06-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_telegram_id_customuser_telegram_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_photo_url',
        ),
    ]
