# Generated by Django 5.2.3 on 2025-06-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='portfolio_holder',
        ),
        migrations.AddField(
            model_name='hero',
            name='first_name',
            field=models.CharField(default='Name', max_length=255),
        ),
        migrations.AddField(
            model_name='hero',
            name='last_name',
            field=models.CharField(default='Surname', max_length=255),
        ),
    ]
